"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function ResetPasswordPage() {
  const router = useRouter();
  const supabase = createClient();
  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState<{ type: "ok" | "err"; text: string } | null>(null);
  const [ready, setReady] = useState(false);

  // v59: Supabase recovery links carry the tokens in the URL hash
  // (#access_token=...&refresh_token=...&type=recovery) OR as ?code= in the
  // query for PKCE. Both must be consumed before updateUser() will work;
  // otherwise the page shows "Auth session missing".
  useEffect(() => {
    (async () => {
      try {
        // 1) Hash-token flow (recovery links generated by admin.generateLink).
        const hash = typeof window !== "undefined" ? window.location.hash : "";
        if (hash.includes("access_token")) {
          const params = new URLSearchParams(hash.replace(/^#/, ""));
          const access_token = params.get("access_token") ?? "";
          const refresh_token = params.get("refresh_token") ?? "";
          if (access_token && refresh_token) {
            await supabase.auth.setSession({ access_token, refresh_token });
            history.replaceState(null, "", window.location.pathname);
          }
        }
        // 2) PKCE ?code= flow (some Supabase auth setups).
        const search = typeof window !== "undefined" ? window.location.search : "";
        if (search.includes("code=")) {
          const p = new URLSearchParams(search);
          const code = p.get("code");
          if (code) {
            await supabase.auth.exchangeCodeForSession(code);
            history.replaceState(null, "", window.location.pathname);
          }
        }
      } catch {
        // fall through — updateUser will still surface a useful error
      } finally {
        setReady(true);
      }
    })();
  }, [supabase]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (password !== confirm) {
      return setMessage({ type: "err", text: "Passwords do not match." });
    }
    if (password.length < 6) {
      return setMessage({ type: "err", text: "Password must be at least 6 characters." });
    }
    setLoading(true);
    setMessage(null);
    const { error } = await supabase.auth.updateUser({ password });
    setLoading(false);
    if (error) return setMessage({ type: "err", text: error.message });
    setMessage({ type: "ok", text: "Password updated. Redirecting to sign in…" });
    setTimeout(() => router.replace("/login"), 2000);
  }

  return (
    <main className="min-h-screen flex items-center justify-center px-4">
      <form
        onSubmit={handleSubmit}
        className="w-full max-w-sm bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 p-8 space-y-4"
      >
        <h1 className="text-2xl font-bold text-center">Set new password</h1>
        <input
          type="password"
          className="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2"
          placeholder="New password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        <input
          type="password"
          className="w-full rounded-lg border border-slate-300 dark:border-slate-700 px-3 py-2"
          placeholder="Confirm new password"
          value={confirm}
          onChange={(e) => setConfirm(e.target.value)}
          required
        />
        <button
          type="submit"
          disabled={loading || !ready}
          className="w-full rounded-lg bg-slate-900 text-white py-2 font-medium disabled:opacity-50"
        >
          {!ready ? "Preparing…" : loading ? "Updating…" : "Update password"}
        </button>
        {message && (
          <p
            className={`text-sm text-center ${
              message.type === "ok" ? "text-emerald-600" : "text-red-600"
            }`}
          >
            {message.text}
          </p>
        )}
      </form>
    </main>
  );
}
